### ISSUE TITLE
Problems building MeetixOS

### ISSUE THREAD

**Issue by lucic71** [MarcoCicognani/MeetixOS#9]
I have an Ubuntu 18.04.6 running on x86. 
I tried to build the project from command line using the instructions from [BuildInstructions.md](https://github.com/MarcoCicognani/MeetixOS/blob/master/Documents/BuildInstructions.md), however I failed when I had to run `ninja run`. These are the steps from my attempt:
```
sudo apt install build-essential gcc g++ cmake ninja-build libmpfr-dev libmpc-dev libgmp-dev qemu-system-x86 qemu-utils grub2-common xorriso patch wget
cd MeetixOS/Toolchain
./Build.sh
cd ../Build
mkdir -p Release
pushd Release
cmake -GNinja -DCMAKE_TOOLCHAIN_FILE=Build/CMakeToolchain.txt -DCMAKE_BUILD_TYPE=Release ../..
popd
cd Release
ninja run
```

I attached three files containing the output of `./Build.sh`, `cmake -GNinja -DCMAKE_TOOLCHAIN_FILE=Build/CMakeToolchain.txt -DCMAKE_BUILD_TYPE=Release ../..` and `ninja run`.
[build.log](https://github.com/MarcoCicognani/MeetixOS/files/8018251/build.log)
[cmake.log](https://github.com/MarcoCicognani/MeetixOS/files/8018255/cmake.log)
[ninja.log](https://github.com/MarcoCicognani/MeetixOS/files/8018257/ninja.log)

Is there any way I can solve this issue or is there any attempt to create a script that can handle the whole build process?

**Comment by MarcoCicognani** [comment]
Hi Lucian,
After a quick glance I think your host toolchain is too old.

I use GCC/G++ v9.3.0 (LinuxMint), by I personally advice GCC/G++ 11, since MeetixOS toolchain is based on this version.

**Comment by MarcoCicognani** [comment]
Try
```
sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
sudo apt update
sudo apt install -y gcc-11 g++-11

cd MeetixOS/Toolchain
export CC=gcc-11
export CXX=g++-11
./Build.sh --rebuild
```

**Comment by MarcoCicognani** [comment]
@lucic71 have you solved the encountered problems?

**Comment by lucic71** [comment]
Not yet, I will come back with a message when I will have some free time to look further into this issue.

**Comment by lucic71** [comment]
I will close the issue as I moved to Arch Linux with GCC 11.1.0 and the problem is not reproducible anymore.
